# # services:
# #   mysql:
# #     image: mysql:9.5
# #     ports:
# #       - "3306:3306"
# #     environment:
# #       - MYSQL_ROOT_PASSWORD=
# #       - MYSQL_ALLOW_EMPTY_PASSWORD=true
# #       - MYSQL_USER=petclinic
# #       - MYSQL_PASSWORD=petclinic
# #       - MYSQL_DATABASE=petclinic
# #     volumes:
# #       - "./conf.d:/etc/mysql/conf.d:ro"
# #   postgres:
# #     image: postgres:18.1
# #     ports:
# #       - "5432:5432"
# #     environment:
# #       - POSTGRES_PASSWORD=petclinic
# #       - POSTGRES_USER=petclinic
# #       - POSTGRES_DB=petclinic


# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: spring-petclinic
#     ports:
#       - "8081:8080"
#     depends_on:
#       - mysql
#     environment:
#       SPRING_PROFILES_ACTIVE: mysql
#       MYSQL_URL: jdbc:mysql://mysql:3306/petclinic
#       MYSQL_USER: petclinic
#       MYSQL_PASSWORD: petclinic

#   mysql:
#     image: mysql:9.5
#     container_name: mysql
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: ""
#       MYSQL_ALLOW_EMPTY_PASSWORD: "true"
#       MYSQL_DATABASE: petclinic
#       MYSQL_USER: petclinic
#       MYSQL_PASSWORD: petclinic
#     volumes:
#       - ./conf.d:/etc/mysql/conf.d:ro

#   postgres:
#     image: postgres:18.1
#     container_name: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_PASSWORD: petclinic
#       POSTGRES_USER: petclinic
#       POSTGRES_DB: petclinic


version: "3.8"

services:
  app:
    build: .
    container_name: spring-petclinic
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      MYSQL_URL: jdbc:mysql://mysql:3306/petclinic
      MYSQL_USER: petclinic
      # MYSQL_PASS: petclinic

  mysql:
    image: mysql:9.5
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:18.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
